#ifndef ARTIFACTUARY_H_INCLUDED
#define ARTIFACTUARY_H_INCLUDED


#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>


#define ARTIFACTUARY_NUM_ARRAYS 9

#define ARTIFACTUARY_BUILDING_0_FACE_0 0
#define ARTIFACTUARY_BUILDING_0_FACE_1 1
#define ARTIFACTUARY_BUILDING_1_FACE_0 2
#define ARTIFACTUARY_BUILDING_1_FACE_1 3
#define ARTIFACTUARY_BUILDING_2_FACE_0 4
#define ARTIFACTUARY_BUILDING_2_FACE_1 5
#define ARTIFACTUARY_BUILDING_3_FACE_0 6
#define ARTIFACTUARY_BUILDING_3_FACE_1 7
#define ARTIFACTUARY_CITYSCAPE 8

#define ARTIFACTUARY_BUILDING_0_FACE_0_WIDTH 10
#define ARTIFACTUARY_BUILDING_0_FACE_0_HEIGHT 15
#define ARTIFACTUARY_BUILDING_0_FACE_1_WIDTH 10
#define ARTIFACTUARY_BUILDING_0_FACE_1_HEIGHT 15
#define ARTIFACTUARY_BUILDING_1_FACE_0_WIDTH 10
#define ARTIFACTUARY_BUILDING_1_FACE_0_HEIGHT 15
#define ARTIFACTUARY_BUILDING_1_FACE_1_WIDTH 10
#define ARTIFACTUARY_BUILDING_1_FACE_1_HEIGHT 15
#define ARTIFACTUARY_BUILDING_2_FACE_0_WIDTH 10
#define ARTIFACTUARY_BUILDING_2_FACE_0_HEIGHT 15
#define ARTIFACTUARY_BUILDING_2_FACE_1_WIDTH 10
#define ARTIFACTUARY_BUILDING_2_FACE_1_HEIGHT 15
#define ARTIFACTUARY_BUILDING_3_FACE_0_WIDTH 10
#define ARTIFACTUARY_BUILDING_3_FACE_0_HEIGHT 25
#define ARTIFACTUARY_BUILDING_3_FACE_1_WIDTH 10
#define ARTIFACTUARY_BUILDING_3_FACE_1_HEIGHT 25
#define ARTIFACTUARY_CITYSCAPE_WIDTH 32
#define ARTIFACTUARY_CITYSCAPE_HEIGHT 17

#define ARTIFACTUARY_NUM_PIXELS \
    (ARTIFACTUARY_BUILDING_0_FACE_0_WIDTH * ARTIFACTUARY_BUILDING_0_FACE_0_HEIGHT + \
     ARTIFACTUARY_BUILDING_0_FACE_1_WIDTH * ARTIFACTUARY_BUILDING_0_FACE_1_HEIGHT + \
     ARTIFACTUARY_BUILDING_1_FACE_0_WIDTH * ARTIFACTUARY_BUILDING_1_FACE_0_HEIGHT + \
     ARTIFACTUARY_BUILDING_1_FACE_1_WIDTH * ARTIFACTUARY_BUILDING_1_FACE_1_HEIGHT + \
     ARTIFACTUARY_BUILDING_2_FACE_0_WIDTH * ARTIFACTUARY_BUILDING_2_FACE_0_HEIGHT + \
     ARTIFACTUARY_BUILDING_2_FACE_1_WIDTH * ARTIFACTUARY_BUILDING_2_FACE_1_HEIGHT + \
     ARTIFACTUARY_BUILDING_3_FACE_0_WIDTH * ARTIFACTUARY_BUILDING_3_FACE_0_HEIGHT + \
     ARTIFACTUARY_BUILDING_3_FACE_1_WIDTH * ARTIFACTUARY_BUILDING_3_FACE_1_HEIGHT + \
     ARTIFACTUARY_CITYSCAPE_WIDTH * ARTIFACTUARY_CITYSCAPE_HEIGHT)


#include "array.h"


extern array_t artifactuary_arrays[ARTIFACTUARY_NUM_ARRAYS];
extern rgba_t artifactuary_array_data[ARTIFACTUARY_NUM_PIXELS];
extern int32_t artifactuary_array_data_mapping[ARTIFACTUARY_NUM_PIXELS];


void artifactuary_init(void);
void artifactuary_process(float time);


#endif
